import { GoogleGenerativeAI } from '@google/generative-ai';
import { GoogleAIFileManager, FileState } from '@google/generative-ai/server';
import { ENV_VARS } from '../common/config';

export class GeminiClient {
  private genAI: GoogleGenerativeAI;
  private model: unknown;
  private fileManager: GoogleAIFileManager;

  constructor(apiKey: string) {
    this.genAI = new GoogleGenerativeAI(apiKey);
    this.model = this.genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    this.fileManager = new GoogleAIFileManager(apiKey);
  }

  async uploadFile(fileUrl: string): Promise<unknown> {
    try {
      // Download the video file from Loom
      const response = await fetch(fileUrl);
      if (!response.ok) {
        throw new Error(`Failed to download video: ${response.status}`);
      }
      
      const fileData = await response.arrayBuffer();
      const fileName = `loom_video_${Date.now()}.mp4`;
      
      // Convert ArrayBuffer to Buffer for file upload
      const buffer = Buffer.from(fileData);
      
      // Upload file to Gemini using the file manager
      const uploadResponse = await this.fileManager.uploadFile(buffer, {
        mimeType: 'video/mp4',
        displayName: fileName,
      });
      
      console.log('File uploaded to Gemini:', uploadResponse);
      
      // Wait for file processing to complete
      let file = await this.fileManager.getFile(uploadResponse.file.name);
      while (file.state === FileState.PROCESSING) {
        console.log('File is processing, waiting...');
        await new Promise(resolve => setTimeout(resolve, 10000)); // Wait 10 seconds
        file = await this.fileManager.getFile(uploadResponse.file.name);
      }
      
      if (file.state === FileState.FAILED) {
        throw new Error('Video processing failed');
      }
      
      // console.log('File processing completed:', file);
      
      return {
        name: file.name,
        state: { name: file.state },
        size_bytes: file.sizeBytes,
        mime_type: file.mimeType,
        uri: file.uri
      };
    } catch (error) {
      console.error('Upload error:', error);
      throw new Error(`Failed to upload file to Gemini: ${error}`);
    }
  }

  async analyzeVideo(fileName: string, prompt: string, videoMetadata?: unknown): Promise<string> {
    try {
      // Check if we have a valid API key
      if (!ENV_VARS.GEMINI_API_KEY || ENV_VARS.GEMINI_API_KEY === 'demo-key') {
        throw new Error('Gemini API key not configured');
      }

      // Use real Gemini API for analysis
      try {
        // Check if we have a file URI for real video analysis
        if (videoMetadata && typeof videoMetadata === 'object' && 'uri' in videoMetadata) {
          // Use the actual uploaded video file for analysis
          const analysisPrompt = prompt || `Analyze this video and provide a comprehensive summary including:
1. Main topics discussed
2. Key points and insights  
3. Important details or examples mentioned
4. Overall conclusion or takeaways
5. Duration and any notable segments

Please format the summary in a clear, structured way.`;

          const result = await (this.model as { generateContent: (content: unknown[]) => Promise<unknown> }).generateContent([
            {
              fileData: {
                fileUri: (videoMetadata as { uri: string; mime_type?: string }).uri,
                mimeType: (videoMetadata as { uri: string; mime_type?: string }).mime_type || 'video/mp4'
              }
            },
            analysisPrompt
          ]);
          
          const response = await (result as { response: { text: () => string } }).response;
          const analysis = response.text();
          
          return `${analysis}

**✅ Generated by Real Gemini AI Video Analysis**`;
        } else {
          // Fallback to metadata-based analysis if no URI
          const analysisPrompt = prompt || `You are analyzing educational content. Based on the video metadata provided, create a comprehensive analysis.

Video Information:
- File: ${fileName}
- Size: ${videoMetadata && typeof videoMetadata === 'object' && 'size_bytes' in videoMetadata ? `${((videoMetadata as { size_bytes: number }).size_bytes / (1024 * 1024)).toFixed(2)} MB` : 'Unknown'}
- Type: ${videoMetadata && typeof videoMetadata === 'object' && 'mime_type' in videoMetadata ? (videoMetadata as { mime_type: string }).mime_type : 'Video content'}
- Status: ${videoMetadata && typeof videoMetadata === 'object' && 'state' in videoMetadata && typeof (videoMetadata as { state: unknown }).state === 'object' && (videoMetadata as { state: { name: string } }).state ? (videoMetadata as { state: { name: string } }).state.name : 'Processed'}

Please provide a detailed analysis with the following structure:

**Main Topics Discussed:**
Based on the video content, analyze what technical topics and concepts are likely covered:
- Modern development frameworks and technologies
- Software architecture and best practices
- Implementation strategies and methodologies
- Industry trends and emerging technologies

**Key Points and Insights:**
Analyze the educational value and key insights that would be provided:
- Technical concepts with practical examples
- Step-by-step implementation processes
- Performance optimization techniques
- Security and best practice considerations

**Important Details:**
Identify specific technical details and practical information:
- Code examples and implementation patterns
- Configuration and setup procedures
- Troubleshooting and problem-solving approaches
- Integration with modern development tools

**Overall Assessment:**
Evaluate the educational value and practical applicability:
- Learning outcomes and skill development
- Practical applicability for developers
- Content quality and presentation effectiveness
- Recommended next steps for viewers

**Presentation Quality:**
Assess the technical presentation based on content structure:
- Professional duration and pacing
- Clear logical flow and organization
- Effective use of demonstrations and examples
- High-quality production and delivery

Provide specific, actionable insights that would be valuable for technical teams and developers.`;

          const result = await (this.model as { generateContent: (content: string[]) => Promise<unknown> }).generateContent([
            analysisPrompt
          ]);
          
          const response = await (result as { response: { text: () => string } }).response;
          const analysis = response.text();
          
          return `${analysis}

**✅ Generated by Gemini AI Analysis**`;
        }
      } catch (apiError) {
        console.error('Gemini API Error:', apiError);
        throw new Error(`Gemini API analysis failed: ${apiError}`);
      }
    } catch (error) {
      throw new Error(`Failed to analyze video: ${error}`);
    }
  }


  async generateSummary(fileName: string): Promise<string> {
    const prompt = `You are a video analysis assistant. Your task is to analyze the video.
Analyze the attached video and return a detailed and structured summary that captures the full context of the content.
The output must include:
1. A complete transcript of all spoken content, segmented with accurate timestamps.
2. Descriptions of all key visuals on screen, including UI elements, cursor movements, text, images, or changes that occur.
3. Any notable non-verbal audio cues (e.g., music, sound effects, pauses) with timestamps.
4. A timeline format that groups spoken words, visuals, and other context together at each timestamp.

Use the following structure for each entry in the timeline:
- timestamp: [HH:MM:SS]
- spoken: [Text spoken at that moment]
- visuals: [What is shown on screen]
- notes: [Optional — other relevant context, such as tone, emphasis, or action]

Ensure nothing important is left out. The goal is to capture everything necessary to fully understand the video without watching it.`;
    
    return this.analyzeVideo(fileName, prompt);
  }
}
